[CmdletBinding()]
param(
    # Harness-owned Hermes home to point at the mock. Created if missing; an
    # existing directory must carry the .phase4-test-home marker.
    [Parameter(Mandatory)][string]$HermesHome,
    [Parameter(Mandatory)][string]$EvidenceDirectory,
    # Defaults to the Node runtime of the default offline install.
    [Parameter()][string]$NodeExe = (Join-Path $env:LOCALAPPDATA 'OfflineHermes\runtime\node\node.exe'),
    [Parameter()][int]$StartTimeoutSeconds = 20
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'Phase4.psm1') -Force

if (-not (Test-Path -LiteralPath $NodeExe -PathType Leaf)) {
    throw "Node runtime not found: $NodeExe`nInstall Offline Hermes first or pass -NodeExe <install>\runtime\node\node.exe."
}
$mockModule = Join-Path (Get-Phase4RepoRoot) 'upstream\hermes-agent\tests-js\scripts\mock-server.ts'
if (-not (Test-Path -LiteralPath $mockModule -PathType Leaf)) {
    throw "Upstream mock server not found: $mockModule"
}

# Never write mock credentials into a real user's Hermes home.
$marker = Join-Path $HermesHome '.phase4-test-home'
if ((Test-Path -LiteralPath $HermesHome) -and -not (Test-Path -LiteralPath $marker)) {
    if (@(Get-ChildItem -LiteralPath $HermesHome -Force).Count -gt 0) {
        throw "Refusing to use ${HermesHome}: it exists, is not empty, and has no .phase4-test-home marker."
    }
}
New-Item -ItemType Directory -Path $HermesHome, $EvidenceDirectory -Force | Out-Null
Set-Content -LiteralPath $marker -Value 'Created by tests/phase4/Start-MockProvider.ps1; safe to delete.'

$stateFile = Join-Path $EvidenceDirectory 'mock-provider-state.json'
Remove-Item -LiteralPath $stateFile -ErrorAction SilentlyContinue
$process = Start-Process -FilePath $NodeExe -PassThru -WindowStyle Hidden `
    -ArgumentList @("`"$(Join-Path $PSScriptRoot 'mock-provider.mjs')`"", "`"$mockModule`"", "`"$stateFile`"") `
    -RedirectStandardOutput (Join-Path $EvidenceDirectory 'mock-provider.stdout.log') `
    -RedirectStandardError (Join-Path $EvidenceDirectory 'mock-provider.stderr.log')

$deadline = [DateTime]::UtcNow.AddSeconds($StartTimeoutSeconds)
$state = $null
while ([DateTime]::UtcNow -lt $deadline) {
    if ($process.HasExited) { break }
    if (Test-Path -LiteralPath $stateFile) {
        try { $state = Get-Content -LiteralPath $stateFile -Raw | ConvertFrom-Json; break } catch { }
    }
    Start-Sleep -Milliseconds 200
}
if (-not $state) {
    if (-not $process.HasExited) { Stop-Process -Id $process.Id -Force }
    $stderr = Get-Content -LiteralPath (Join-Path $EvidenceDirectory 'mock-provider.stderr.log') -Raw -ErrorAction SilentlyContinue
    throw "Mock provider did not start within $StartTimeoutSeconds s.`n$stderr"
}

# Same provider shape upstream's dev:mock flow writes (writeMockConfig in
# mock-server.ts), plus the offline-profile settings.
$config = @"
# Generated by tests/phase4/Start-MockProvider.ps1 for Phase 4 smoke tests.
model:
  default: mock-model
  provider: mock
providers:
  mock:
    api: $($state.url)/v1
    name: Mock
    api_mode: chat_completions
    key_env: MOCK_API_KEY
    models:
      mock-model: {}
    context_length: 64000
updates:
  check: false
telemetry:
  shared_metrics:
    enabled: false
    send: false
"@
[IO.File]::WriteAllText((Join-Path $HermesHome 'config.yaml'), $config, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText((Join-Path $HermesHome '.env'), "MOCK_API_KEY=phase4-mock-placeholder`n", [Text.UTF8Encoding]::new($false))

Write-Host "Mock provider listening on $($state.url) (pid $($process.Id)); test home $HermesHome"
[pscustomobject]@{
    ProcessId = $process.Id
    Url = $state.url
    StateFile = $stateFile
    HermesHome = $HermesHome
    Reply = $state.reply
}
